/**
 * TacticalAlerts
 *
 * Displays tactical warnings generated by the battle analysis engine.
 * Alerts are color-coded by severity and show which enemy Pokémon
 * triggered the warning.
 */

import React, { memo } from 'react';
import { StyleSheet, View as RNView, ScrollView, ActivityIndicator } from 'react-native';
import { Text } from '@/components/Themed';
import { TacticalAlert, AlertSeverity } from '@/src/utils/battle-analysis';

interface Props {
  alerts: TacticalAlert[];
  loading: boolean;
}

const SEVERITY_STYLE: Record<AlertSeverity, { border: string; bg: string; badge: string }> = {
  danger:  { border: '#dc2626', bg: 'rgba(220,38,38,0.08)',  badge: '#dc2626' },
  warning: { border: '#f97316', bg: 'rgba(249,115,22,0.08)', badge: '#f97316' },
  info:    { border: '#3b82f6', bg: 'rgba(59,130,246,0.08)', badge: '#3b82f6' },
};

const SEVERITY_LABEL: Record<AlertSeverity, string> = {
  danger:  'DANGER',
  warning: 'WARNING',
  info:    'INFO',
};

const AlertCard = memo(({ alert }: { alert: TacticalAlert }) => {
  const s = SEVERITY_STYLE[alert.severity];
  return (
    <RNView style={[styles.card, { borderLeftColor: s.border, backgroundColor: s.bg }]}>
      <RNView style={styles.cardHeader}>
        <Text style={styles.icon}>{alert.icon}</Text>
        <RNView style={styles.cardTitleBlock}>
          <RNView style={styles.titleRow}>
            <RNView style={[styles.badge, { backgroundColor: s.badge }]}>
              <Text style={styles.badgeText}>{SEVERITY_LABEL[alert.severity]}</Text>
            </RNView>
            <Text style={styles.title} numberOfLines={1}>{alert.title}</Text>
          </RNView>
          <Text style={styles.description}>{alert.description}</Text>
        </RNView>
      </RNView>
    </RNView>
  );
});

export function TacticalAlerts({ alerts, loading }: Props) {
  const dangerAlerts  = alerts.filter(a => a.severity === 'danger');
  const warningAlerts = alerts.filter(a => a.severity === 'warning');
  const infoAlerts    = alerts.filter(a => a.severity === 'info');

  return (
    <RNView style={styles.wrapper}>
      <Text style={styles.sectionLabel}>TACTICAL ALERTS</Text>

      {loading ? (
        <RNView style={styles.centered}>
          <ActivityIndicator size="small" color="#d4af37" />
          <Text style={styles.loadingText}>Analyzing...</Text>
        </RNView>
      ) : alerts.length === 0 ? (
        <RNView style={styles.centered}>
          <Text style={styles.emptyText}>
            {'\u2714'} No critical alerts detected
          </Text>
        </RNView>
      ) : (
        <>
          {dangerAlerts.map(a  => <AlertCard key={a.id} alert={a} />)}
          {warningAlerts.map(a => <AlertCard key={a.id} alert={a} />)}
          {infoAlerts.map(a   => <AlertCard key={a.id} alert={a} />)}
        </>
      )}
    </RNView>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    paddingHorizontal: 14,
    paddingBottom: 30,
  },
  sectionLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    color: 'rgba(255,255,255,0.28)',
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  card: {
    borderLeftWidth: 3,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  icon: {
    fontSize: 20,
    marginTop: 1,
  },
  cardTitleBlock: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  badge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
  },
  badgeText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: 'bold',
    letterSpacing: 0.8,
  },
  title: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
    flex: 1,
    textTransform: 'capitalize',
  },
  description: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    lineHeight: 17,
  },
  centered: {
    paddingVertical: 20,
    alignItems: 'center',
    gap: 8,
  },
  loadingText: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: 13,
  },
  emptyText: {
    color: '#4ade80',
    fontSize: 13,
    fontWeight: '600',
  },
});
